name: check-deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          git config --global user.email "msub2official@gmail.com"
          git config --global user.name "msub2"
          npm install
          npm run deploy